development: &default
  button:
    -
      type: click
      name: 系列
      key: serie
    -
      type: click
      name: 随便看看
      key: lookingaround
    -
      name: 更多
      sub_button:
        -
          type: click
          name: 关于
          key: about
        -
          type: view
          name: 绑定
          url: "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx1532dfc6d2da9dcf&redirect_uri=http://5tv.com/bind&response_type=code&scope=snsapi_base&state=123#wechat_redirect"
        -
          type: view
          name: 建议
          url: "http://5tv.com/"
        -
          type: click
          name: 我的试片
          key: previews
test: 
  <<: *default

production:
  <<: *default
