development: &default
  button:
    #-
      #name: 5爱追剧
      #sub_button: 
        #-
          #type: click
          #name: 经典神速剧
          #key: classic
        #-
          #type: click
          #name: 搞笑系列剧
          #key: joke
        #-
          #type: click
          #name: 点我看更多
          #key: click_for_more
    # -
    #   # name: 5爱活动
    #   name: 欢乐赢电视
    #   type: view
    #   url: http://5tv.com/weixin_supporters/mobi_show_p1
    #   # sub_button:
    #   #   -
    #   #     type: click
    #   #     name: 欢乐赢电视
    #   #     key: get_tv
    #   #   -
    #   #     type: view
    #   #     name: 没事玩游戏
    #   #     url: http://104.237.155.77/weixinapi/game_random
    -
      name: APP下载
      sub_button:
        -
          type: view
          name: 绑定账号
          url: "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx1532dfc6d2da9dcf&redirect_uri=http://weixintest.5tv.com/bind&response_type=code&scope=snsapi_base&state=123#wechat_redirect"
        #-
          #type: click
          #name: 我的追剧
          #key: follows
        #-
          #type: view
          #name: app下载
          ##url: http://5tv.com/app_downloads/show?newest=true  
          #url: https://itunes.apple.com/us/app/5tv-shou-ji-ju/id940044276?l=zh&ls=1&mt=8
        # -
        #   type: click
        #   name: 勾搭5娘
        #   key: pickup
test: 
  <<: *default

production:
  button:
    -
      name: APP下载
      sub_button:
        -
          type: view
          name: app下载
          #url: http://5tv.com/app_downloads/show?newest=true  
          url: https://itunes.apple.com/us/app/5tv-shou-ji-ju/id940044276?l=zh&ls=1&mt=8
        # -
        #   type: click
