development: &default
  appid: wx1532dfc6d2da9dcf
  appsecret: 93ed294ed4b3dd8979683d710926e5fb
  token: xiukeshibukezhanshengde
  wx_account_id: gh_4c161956300a
test: 
  <<: *default

production:
  <<: *default