development: &default
  appid: wx1532dfc6d2da9dcf
  appsecret: 93ed294ed4b3dd8979683d710926e5fb
  token: xiukeshibukezhanshengde
  wx_account_id: gh_4c161956300a
  test_open_id: ou3rnjq7Tx-Nvii_XhUINYhCISYo
test: 
  <<: *default

production:
  appid: wx09a8a54a7050bdf0
  appsecret: d643e367f0449fe8391254bd2e439070
  token: xiukeshibukezhanshengde
  wx_account_id: gh_105842a55763
